[package]
name = "janim-backend"
version = "5.0.3"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "janim_backend"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.29.0", features = ["experimental-inspect"] }
numpy = "0.29.0"
# i18n
rust-i18n = "4.2.1"
serde_yaml = "0.9.34"
# macros
pyresolver = { path = "./macros/pyresolver" }
# others
anyhow = "1.0.104"
bytemuck = "1.25.2"
ndarray = "0.17.2"
nalgebra = "0.35.0"

[package.metadata.i18n]
available-locales = ["en", "zh_CN"]
default-locale = "en"
